"""Re-apply the LLM-dedup decisions across an OCR/extraction change.

The dedup ledger (data/services/dedup/llm_merges.jsonl) keys merge groups on
version_ids like "col1936-L58354.v". Those line-ids are regenerated by every
re-extraction, so after new OCR the ledger would be orphaned. This script ports
the decisions: it matches each merge member's stable CONTENT fingerprint
(edition + name + birth + first events, from llm_merges_fingerprinted.jsonl) to a
version_id in the CURRENT ParsedEntry set, and writes a fresh version_id-keyed
ledger.

Matching is within-edition: a fingerprint only competes against entries from the
same edition year, scored by surname+given fuzzy similarity, birth-year agreement,
and shared (year, place, position) events. Robust to OCR drift in the names/text.

  python3 reapply_dedup_fingerprints.py --self-test    # must recover current ledger ~100%
  python3 reapply_dedup_fingerprints.py --write out.jsonl --min-score 70
"""
from __future__ import annotations
import argparse, json, re
from collections import defaultdict
from pathlib import Path
from rapidfuzz import fuzz

from col_match.config import Config
from col_match.services.schema import ParsedEntry

cfg = Config.from_env(); DD = Path(cfg.data_dir)
FP = DD / "dedup" / "llm_merges_fingerprinted.jsonl"

ap = argparse.ArgumentParser()
ap.add_argument("--self-test", action="store_true")
ap.add_argument("--write", default="")
ap.add_argument("--min-score", type=float, default=60.0,
                help="reject a remap below this composite score (flag for review)")
args = ap.parse_args()

def edition(vid):
    m = re.match(r"([a-z]+\d{4})", vid); return m.group(1) if m else vid.split("-")[0]

# current per-version source content, indexed by edition
pe = {}
by_ed = defaultdict(list)
for name in ("llm.jsonl", "rules.jsonl"):
    p = DD / "parsed" / name
    if p.exists():
        for l in p.open():
            r = ParsedEntry.model_validate_json(l)
            pe[r.version_id] = r
            by_ed[edition(r.version_id)].append(r)

def ev_set(r):
    return {(e.year_start, (e.place or "")[:24].lower(), (e.position or "")[:36].lower())
            for e in r.events if e.year_start}

def score(fpr, r):
    s = fuzz.token_set_ratio((fpr.get("surname") or ""), (r.surname or "")) * 0.35
    s += fuzz.token_set_ratio((fpr.get("given") or ""), (r.given_names or "")) * 0.25
    if fpr.get("birth") and r.birth_year:
        s += 15 if abs(fpr["birth"] - r.birth_year) <= 1 else 0
    elif not fpr.get("birth") and not r.birth_year:
        s += 5
    # event overlap (the strongest, OCR-robust signal)
    fev = {(y, p, pos) for (y, p, pos) in (tuple(x) for x in fpr.get("events", []))}
    rev = ev_set(r)
    if fev:
        yr_match = len({y for (y, *_ ) in fev} & {y for (y, *_ ) in rev})
        s += 25 * (yr_match / max(1, len({y for (y, *_ ) in fev})))
    return s

def remap_one(fpr):
    """Return (best_version_id, score). Restrict to same edition."""
    ed = fpr.get("edition") or edition(fpr["version_id"])
    cands = by_ed.get(ed, [])
    if not cands:
        return None, 0.0
    best, bs = None, -1.0
    for r in cands:
        sc = score(fpr, r)
        if sc > bs:
            best, bs = r.version_id, sc
    return best, bs

groups = [json.loads(l) for l in FP.open()]

if args.self_test:
    exact = total = below = 0
    worst = []
    for g in groups:
        for fpr in g["fingerprints"]:
            total += 1
            got, sc = remap_one(fpr)
            if got == fpr["version_id"]:
                exact += 1
            else:
                worst.append((fpr["version_id"], got, round(sc, 1)))
            if sc < args.min_score:
                below += 1
    print(f"self-test: {exact}/{total} fingerprints remap to their ORIGINAL version_id "
          f"({100*exact/total:.1f}%) | below min-score({args.min_score}): {below}")
    if worst:
        print(f"  {len(worst)} mismatches (expected ~0 on unchanged data); sample:")
        for w in worst[:10]:
            print("   want %s got %s score=%s" % w)
    raise SystemExit

if args.write:
    out = Path(args.write); n_ok = n_low = 0
    with out.open("w") as fh:
        for g in groups:
            remapped, scores, flags = [], [], []
            for fpr in g["fingerprints"]:
                got, sc = remap_one(fpr); scores.append(round(sc, 1))
                remapped.append(got)
                if sc < args.min_score: flags.append(got)
            n_ok += sum(1 for s in scores if s >= args.min_score)
            n_low += len(flags)
            fh.write(json.dumps({
                "versions": remapped, "bios": g.get("bios"), "reason": g.get("reason", ""),
                "confidence": g.get("confidence", "high"), "source": g.get("source"),
                "remap_scores": scores, "low_confidence_members": flags}) + "\n")
    print(f"wrote remapped ledger -> {out} | members>=min-score: {n_ok} | flagged-low: {n_low}")
    raise SystemExit

print("specify --self-test or --write <path>")
