"""Place gazetteer for clause parsing: decides whether the tail segment of a
career clause is a colony/territory (place) or part of the position string.

Built from the graph's own colony vocabulary (data/services/gazetteer_graph.json,
fetched read-only from COL_Official.colony + COL_Territory.name) plus the
printed abbreviations the services sections actually use.
"""

from __future__ import annotations

import json
import re
from functools import lru_cache
from pathlib import Path

# Printed abbreviation -> canonical-ish expansion. Keys are normalized
# (lowercase, no dots/apostrophes). Grown from era samples; coverage gaps
# show up in parse stats as unplaced events, not as errors.
ABBREV = {
    "gc": "Gold Coast", "gconst": "Gold Coast", "gcconst": "Gold Coast",
    "sl": "Sierra Leone", "nig": "Nigeria", "snigeria": "Southern Nigeria",
    "snig": "Southern Nigeria", "nnig": "Northern Nigeria", "enig": "Eastern Nigeria",
    "wnig": "Western Nigeria", "lagos": "Lagos",
    "ken": "Kenya", "eap": "East Africa Protectorate", "uga": "Uganda",
    "tang": "Tanganyika", "tganyika": "Tanganyika", "zanz": "Zanzibar",
    "nyasa": "Nyasaland", "nrhod": "Northern Rhodesia", "srhod": "Southern Rhodesia",
    "som": "Somaliland", "bca": "British Central Africa",
    "hk": "Hong Kong", "ss": "Straits Settlements", "fms": "Federated Malay States",
    "mal": "Malaya", "sar": "Sarawak", "nborneo": "North Borneo", "brun": "Brunei",
    "cey": "Ceylon", "maur": "Mauritius", "sey": "Seychelles",
    "cyp": "Cyprus", "pal": "Palestine", "tjordan": "Trans-Jordan", "aden": "Aden",
    "gib": "Gibraltar", "malta": "Malta",
    "jca": "Jamaica", "jam": "Jamaica", "bg": "British Guiana", "brguiana": "British Guiana",
    "trin": "Trinidad", "tdad": "Trinidad", "bhond": "British Honduras",
    "barb": "Barbados", "gren": "Grenada", "stv": "St. Vincent", "stl": "St. Lucia",
    "stlucia": "St. Lucia", "dom": "Dominica", "ant": "Antigua", "stk": "St. Kitts",
    "nev": "Nevis", "monts": "Montserrat", "bah": "Bahamas", "berm": "Bermuda",
    "lwds": "Leeward Islands", "wwds": "Windward Islands", "wi": "West Indies",
    "nsw": "New South Wales", "vic": "Victoria", "qld": "Queensland",
    "saus": "South Australia", "waus": "Western Australia", "tas": "Tasmania",
    "nz": "New Zealand", "natal": "Natal", "cgh": "Cape of Good Hope",
    "cape": "Cape of Good Hope", "ofs": "Orange Free State", "transvaal": "Transvaal",
    "basuto": "Basutoland", "bech": "Bechuanaland", "swazi": "Swaziland",
    "falk": "Falkland Islands", "falkis": "Falkland Islands",
    "fiji": "Fiji", "wpac": "Western Pacific", "png": "Papua New Guinea",
    "gilbert": "Gilbert and Ellice Islands", "sthelena": "St. Helena",
    "gambia": "Gambia", "co": "Colonial Office", "do": "Dominions Office",
    "nfld": "Newfoundland", "nbrunswick": "New Brunswick", "ns": "Nova Scotia",
    "bc": "British Columbia", "stsettlements": "Straits Settlements",
    # directional / dotted place forms the services sections use ("N. Rhodesia",
    # "W. Australia", "B. Guiana") — normalized (dots/spaces stripped). Without
    # these the abbreviated place is misread as part of the position string.
    "nrhodesia": "Northern Rhodesia", "srhodesia": "Southern Rhodesia",
    "waustralia": "Western Australia", "waust": "Western Australia",
    "saustralia": "South Australia", "saust": "South Australia",
    "naustralia": "Australia", "eaustralia": "Australia",
    "bguiana": "British Guiana", "bhonduras": "British Honduras",
    "nnigeria": "Northern Nigeria", "enigeria": "Eastern Nigeria",
    "wnigeria": "Western Nigeria", "scameroons": "Cameroons",
    "ncameroons": "Cameroons", "turksisl": "Turks and Caicos Islands",
    "swafrica": "South West Africa",
    "eafrica": "East Africa", "wafrica": "West Africa",
}

_NORM = re.compile(r"[^a-z]")


def norm(s: str) -> str:
    return _NORM.sub("", s.lower())


@lru_cache(maxsize=4)
def _load_rollup(data_dir: str) -> dict[str, str]:
    """Grounded place -> record-colony roll-up (capitals + KG federation
    membership), generated by build_place_rollup.py from capital_audit +
    empire-evolution-wpcs. {place_norm: colony_norm}."""
    path = Path(data_dir) / "place_rollup.json"
    if not path.exists():
        return {}
    raw = json.loads(path.read_text())
    return {k: norm(v["colony"]) for k, v in raw.items() if v.get("colony")}


@lru_cache(maxsize=1)
def load(data_dir: str) -> set[str]:
    """Normalized vocabulary of known places."""
    vocab: set[str] = set(map(norm, ABBREV.values()))
    vocab.update(ABBREV.keys())
    path = Path(data_dir) / "gazetteer_graph.json"
    if path.exists():
        g = json.loads(path.read_text())
        for name in g.get("colonies", []) + g.get("territories", []):
            vocab.add(norm(name))
    vocab.update(_load_rollup(data_dir))  # grounded capitals/members are valid places
    return vocab


# printed place -> the graph colony/ies the resulting stint would sit under
# (normalized on both sides). A set because some printed names are genuinely
# ambiguous across graph colonies ("Malaya"): match succeeds if the stint's
# colony is any member.
PLACE_ALIASES: dict[str, set[str]] = {
    "malaya": {"federationofmalaya", "federatedmalaystates", "unfederatedmalaystates"},
    "eastafricaprotectorate": {"britisheastafricaandzanzibar", "kenya"},
    "somaliland": {"britishsomaliland"},
    "stkitts": {"stchristopherandnevis"},
    "nevis": {"stchristopherandnevis"},
    "johore": {"unfederatedmalaystates", "federationofmalaya"},
    "kedah": {"unfederatedmalaystates", "federationofmalaya"},
    "kelantan": {"unfederatedmalaystates", "federationofmalaya"},
    "trengganu": {"unfederatedmalaystates", "federationofmalaya"},
    "perlis": {"unfederatedmalaystates", "federationofmalaya"},
    # Straits Settlements component territories — Singapore, Penang (a.k.a.
    # Prince of Wales Island), Malacca, Province Wellesley, Dindings; Labuan and
    # the Cocos/Christmas Islands were SS-administered for most of the period.
    # Records are filed under "Straits Settlements"; biographies name the
    # district, so without this roll-up every such clause disagrees on colony.
    "singapore": {"straitssettlements"},
    "penang": {"straitssettlements"},
    "princeofwalesisland": {"straitssettlements"},
    "malacca": {"straitssettlements"},
    "provincewellesley": {"straitssettlements"},
    "dindings": {"straitssettlements"},
    "labuan": {"straitssettlements"},
    "cocosislands": {"straitssettlements"},
    "christmasisland": {"straitssettlements"},
    # Federated Malay States (from 1895): Perak, Selangor, Negri Sembilan,
    # Pahang. Kuala Lumpur is the FMS capital (in Selangor); Kinta/Larut/Krian
    # are Perak districts; Sungei Ujong a Negri Sembilan predecessor state.
    "perak": {"federatedmalaystates"},
    "selangor": {"federatedmalaystates"},
    "negrisembilan": {"federatedmalaystates"},
    "pahang": {"federatedmalaystates"},
    "kualalumpur": {"federatedmalaystates"},
    "kinta": {"federatedmalaystates"},
    "larut": {"federatedmalaystates"},
    "krian": {"federatedmalaystates"},
    "sungeiujong": {"federatedmalaystates"},
    # printed compound label used in the later editions
    "straitssettlementsandfederatedmalaystates":
        {"straitssettlements", "federatedmalaystates"},
    "federatedmalaystatesandstraitssettlements":
        {"straitssettlements", "federatedmalaystates"},
    # Tanganyika records are filed under "Tanganyika"; bios say "Tanganyika
    # Territory". Quebec/Manitoba roll up to Canada (cf. Ontario/Nova Scotia).
    "tanganyikaterritory": {"tanganyika"},
    "quebec": {"canada"},
    "manitoba": {"canada"},
    "ashanti": {"goldcoast"},
    "westernnigeria": {"nigeria"},
    "easternnigeria": {"nigeria"},
    "northernnigeria": {"nigeria", "northernnigeria"},
    "southernnigeria": {"nigeria", "southernnigeria"},
    "cameroons": {"nigeria"},
    "tanganyika": {"tanganyika", "tanganyikaterritory"},
    "novascotia": {"canada", "novascotia"},
    "newbrunswick": {"canada", "newbrunswick"},
    "ontario": {"canada"},
    "zanzibar": {"zanzibar", "britisheastafricaandzanzibar"},
    "kenya": {"kenya", "britisheastafricaandzanzibar", "kenyaanduganda"},
    # "East Africa" (bare) is the period shorthand for the East Africa
    # Protectorate, renamed Kenya in 1920; records appear under both.
    "eastafrica": {"eastafrica", "eastafricaprotectorate", "kenya",
                   "britisheastafricaandzanzibar"},
    # Union of South Africa (1910): formed from Cape of Good Hope, Natal,
    # Transvaal and the Orange River Colony (ex-Orange Free State). Records are
    # filed under "South Africa" / "Union of South Africa" while biographies
    # name the province; roll the provinces UP to the union (additive — the
    # province target is kept, and tenure/position/initials still re-gate).
    "transvaal": {"transvaal", "southafrica", "unionofsouthafrica"},
    "capeofgoodhope": {"capeofgoodhope", "southafrica", "unionofsouthafrica"},
    "capecolony": {"capecolony", "capeofgoodhope", "southafrica", "unionofsouthafrica"},
    "capeprovince": {"capeprovince", "capeofgoodhope", "southafrica", "unionofsouthafrica"},
    "natal": {"natal", "southafrica", "unionofsouthafrica"},
    "orangefreestate": {"orangefreestate", "orangerivercolony", "southafrica",
                        "unionofsouthafrica"},
    "orangerivercolony": {"orangerivercolony", "orangefreestate", "southafrica",
                          "unionofsouthafrica"},
    "eastafricaprotectorate": {"eastafricaprotectorate", "eastafrica",
                               "britisheastafricaandzanzibar", "kenya"},
    "uganda": {"uganda", "kenyaanduganda"},
    # Tanga is a province of Tanganyika.
    "tanga": {"tanga", "tanganyika", "tanganyikaterritory"},
    # Leeward Islands federation: records filed under "Leeward Islands"; bios
    # name the presidency (Antigua, St Kitts-Nevis, Dominica [until 1940],
    # Montserrat, Virgin Islands).
    "antigua": {"antigua", "leewardislands"},
    "stkitts": {"stkitts", "stchristopherandnevis", "leewardislands"},
    "stchristopher": {"stchristopher", "stchristopherandnevis", "leewardislands"},
    "nevis": {"nevis", "stchristopherandnevis", "leewardislands"},
    "montserrat": {"montserrat", "leewardislands"},
    "virginislands": {"virginislands", "leewardislands"},
    # Dominica: Leeward until 1940, then Windward — allow both.
    "dominica": {"dominica", "leewardislands", "windwardislands"},
    # Windward Islands federation: Grenada, St Vincent, St Lucia (and Barbados,
    # the early seat).
    "grenada": {"grenada", "windwardislands"},
    "stvincent": {"stvincent", "windwardislands"},
    "stlucia": {"stlucia", "windwardislands"},
    "barbados": {"barbados", "windwardislands"},
    "trinidad": {"trinidad", "trinidadandtobago"},
    "tobago": {"tobago", "trinidadandtobago"},
    # Australian states roll up to the Commonwealth (cf. Canadian provinces).
    "southaustralia": {"southaustralia", "australia", "commonwealthofaustralia"},
    "westernaustralia": {"westernaustralia", "australia", "commonwealthofaustralia"},
    "victoria": {"victoria", "australia", "commonwealthofaustralia"},
    "newsouthwales": {"newsouthwales", "australia", "commonwealthofaustralia"},
    "queensland": {"queensland", "australia", "commonwealthofaustralia"},
    "tasmania": {"tasmania", "australia", "commonwealthofaustralia"},
    "westindies": {"westindiesfederation"},
}


def colony_targets(place: str | None, data_dir: str) -> set[str]:
    """Normalized graph-colony names a printed place can correspond to."""
    canonical = lookup(place or "", data_dir) or (place or "")
    n = norm(canonical)
    if not n:
        return set()
    targets = PLACE_ALIASES.get(n, {n}) | {n}
    roll = _load_rollup(data_dir).get(n)
    if roll:
        targets.add(roll)
    return targets


_TRAILING_NOISE = re.compile(r"\s+(colony|col|protectorate|prot|terr)\.?$", re.I)
# dotted office abbreviations, matched case-sensitively in clause text
_OFFICE = {"C.O.": "Colonial Office", "D.O.": "Dominions Office"}
_OFFICE_RE = re.compile(r"\b([CD]\.\s?O\.)(?=[\s,.)]|$)")


def lookup(segment: str, data_dir: str) -> str | None:
    """Return the place string if `segment` names a known place, else None."""
    seg = segment.strip().rstrip(".")
    if not seg:
        return None
    vocab = load(data_dir)
    for cand in (seg, _TRAILING_NOISE.sub("", seg)):
        n = norm(cand)
        if n and n in vocab:
            return ABBREV.get(n, cand)
    return None


def lookup_prefix(segment: str, data_dir: str) -> str | None:
    """Place named at the START of a segment ("Ceylon civ. ser.",
    "G.C. rwy.", "Basutoland mounted police") — longest prefix wins."""
    words = segment.strip().split()
    for k in range(min(4, len(words) - 1), 0, -1):
        hit = lookup(" ".join(words[:k]), data_dir)
        if hit is not None:
            return hit
    return None


def lookup_office(clause: str) -> str | None:
    """Dotted office abbreviations anywhere in the clause ("assigned to the
    C.O.", "retld. to C.O. as ..."). Case-sensitive to avoid 'Field Co.'."""
    m = _OFFICE_RE.search(clause)
    if m:
        return _OFFICE[m.group(1).replace(" ", "")]
    return None
